import routes from './routes'
import * as api from './api'

export default {
  name: 'ticket',
  routes,
  api,

  nav: {
    title: '工单管理',
    icon: 'bi-ticket-perforated',
    path: '/tickets',
    order: 10,
    group: '业务',
    routeName: 'TicketList',
    children: ['TicketDetail', 'TicketCreate'],
  },

  features: [
    { name: 'list', endpoint: 'GET /tickets/', status: 'done' },
    { name: 'getById', endpoint: 'GET /tickets/:id', status: 'done' },
    { name: 'create', endpoint: 'POST /tickets/', status: 'done' },
    { name: 'update', endpoint: 'PUT /tickets/:id', status: 'done' },
    { name: 'delete', endpoint: 'DELETE /tickets/:id', status: 'done' },
    { name: 'changeStatus', endpoint: 'PUT /tickets/:id/status', status: 'done' },
    { name: 'confirmPayment', endpoint: 'POST /tickets/:id/pay', status: 'done' },
    { name: 'batchAction', endpoint: 'POST /tickets/batch', status: 'done' },
    { name: 'getStatusStats', endpoint: 'GET /tickets/stats', status: 'done' },
    { name: 'getStatusFlow', endpoint: 'GET /tickets/status-flow', status: 'done' },
    { name: 'getServiceItems', endpoint: 'GET /tickets/:id/service-items', status: 'done' },
    { name: 'addServiceItem', endpoint: 'POST /tickets/:id/service-items', status: 'done' },
    { name: 'updateServiceItem', endpoint: 'PUT /tickets/:id/service-items/:itemId', status: 'done' },
    { name: 'deleteServiceItem', endpoint: 'DELETE /tickets/:id/service-items/:itemId', status: 'done' },
    { name: 'batchServiceItems', endpoint: 'POST /tickets/:id/service-items/batch', status: 'done' },
    { name: 'addMaterial', endpoint: 'POST /tickets/:id/materials', status: 'done' },
    { name: 'deleteMaterial', endpoint: 'DELETE /tickets/:id/materials/:materialId', status: 'done' },
    { name: 'updateMaterial', endpoint: 'PUT /tickets/:id/materials/:materialId', status: 'done' },
    { name: 'getMaterialsTrace', endpoint: 'GET /tickets/:id/materials/trace', status: 'done' },
    { name: 'getPhotos', endpoint: 'GET /tickets/:id/photos', status: 'done' },
    { name: 'uploadPhotos', endpoint: 'POST /tickets/:id/photos', status: 'done' },
    { name: 'deletePhoto', endpoint: 'DELETE /tickets/:id/photos', status: 'done' },
    { name: 'getTimeline', endpoint: 'GET /tickets/:id/timeline', status: 'done' },
    { name: 'linkEquipment', endpoint: 'POST /tickets/:id/link-equipment', status: 'done' },
    { name: 'unlinkEquipment', endpoint: 'DELETE /tickets/:id/equipment/:equipmentId', status: 'done' },
    { name: 'startTimer', endpoint: 'POST /tickets/:id/timer/start', status: 'done' },
    { name: 'stopTimer', endpoint: 'POST /tickets/:id/timer/stop', status: 'done' },
    { name: 'getTimerStatus', endpoint: 'GET /tickets/:id/timer/status', status: 'done' },
    { name: 'getProfit', endpoint: 'GET /tickets/:id/profit', status: 'done' },
    { name: 'getProfitList', endpoint: 'GET /tickets/profit-list', status: 'done' },
    { name: 'setDiscount', endpoint: 'PUT /tickets/:id/discount', status: 'done' },
    { name: 'getHistory', endpoint: 'GET /tickets/:id/history', status: 'done' },
    { name: 'getDelta', endpoint: 'GET /tickets/:id/delta', status: 'done' },
    { name: 'confirmDelete', endpoint: 'GET /tickets/:id/confirm-delete', status: 'done' },
    { name: 'doConfirmDelete', endpoint: 'POST /tickets/:id/confirm-delete', status: 'done' },
    { name: 'batchPreview', endpoint: 'POST /tickets/batch-preview', status: 'done' },
    { name: 'batchConfirm', endpoint: 'POST /tickets/batch-confirm', status: 'done' },
    { name: 'batchByFilter', endpoint: 'POST /tickets/batch-by-filter', status: 'done' },
    { name: 'parse', endpoint: 'POST /tickets/parse', status: 'done' },
  ]
}
